# Generated by Django 5.1.4 on 2025-01-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('addr', models.TextField(max_length=50)),
            ],
        ),
    ]
