# Generated by Django 5.1.4 on 2025-01-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='addr',
            field=models.TextField(),
        ),
    ]
