# Generated by Django 5.1.4 on 2025-01-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_detail_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='addr',
            field=models.CharField(max_length=250),
        ),
    ]
